---
title: "DATA622 | Machine Learning and Big Data"
author: "Gabriella Martinez"
date: "5/14/2023"
output:
      html_document:
        toc: yes
        toc_float: yes
        theme: yeti
        highlight: kate
        font-family: "Arial"
        code_folding: show
---
# Final Project
**Exploratory analysis and essay**  

1. Choose a dataset. You get to decide which dataset you want to work on. The data set must be different from the ones used in previous homeworks You can work on a problem from your job, or something you are interested in. You may also obtain a dataset from sites such as Kaggle, Data.Gov, Census Bureau, USGS or other open data portals.   
2. Select one of the methodologies studied in weeks 1-10, and another methodology from weeks 11-15 to apply in the new dataset selected.  
3. To complete this task:  
    a. Describe the problem you are trying to solve.  
    b. Describe your datasets and what you did to prepare the data for analysis.  
    c. Methodologies you used for analyzing the data  
    d. What's the purpose of the analysis performed  
    e. Make your conclusions from your analysis. Please be sure to address the business impact (it could be of any domain) of your solution.  
  
**Deliverable**  

1. Your final presentation should incliude:    
    a. The traditional R file or Python file and essay  
    b. An Essay (minimum 500 word document) or Video (5 to 8 minutes recording). Include the execution and explanation of your code. The video can be recorded on any platform of your choice (Youtube, Free Cam).


<!------- Below is for removing excessive space in Rmarkdown | HTML formatting -------->

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>